baseURL = "https://ntk148v.github.io/mammam"
languageCode = "en-us"
title = "Măm Măm"
theme = "cuisine-book"
enableGitInfo = true

[params]
  author = "Kien Nguyen Tuan"
  description = "Măm Măm"
  logo = "SeekPng.com_doughnut-png_4429089.png"
  comment = true
  # Set source repository location.
  repo = 'https://github.com/ntk148v/mammam'
  # Enable 'Edit' links.
  # Disabled by default. Uncomment to enable. Requires 'repo' param.
  # Path must point to the site directory.
  editpath = 'edit/master'
  # Enable 'Add' links.
  # Disabled by default. Uncomment to enable. Requires 'repo' param.
  # Path must point to the site directory.
  newpath = 'new/master'

