baseURL = "https://ntk148v.github.io/mammam"
languageCode = "en-us"
title = "Măm Măm"
theme = "cuisine-book"

[params]
  author = "Kien Nguyen Tuan"
  description = "Măm Măm"
  logo = "SeekPng.com_doughnut-png_4429089.png"
